services:
  service1_v1_1:
    image: harbor.treok.eu/devops_project_nctesa/service1:${SERVICE1_TAG}
    build: ./service1
    container_name: service1${SERVICE_NAME_SUFFIX}
    restart: "on-failure:5"
    expose:
      - "5000"
    depends_on:
      - service2_v1_1
      - storage
    networks:
      - micro_network

  service2_v1_1:
    image: harbor.treok.eu/devops_project_nctesa/service2:${SERVICE2_TAG}
    build: ./service2
    container_name: service2${SERVICE_NAME_SUFFIX}
    restart: "on-failure:5"
    expose:
      - "5001"
    networks:
      - micro_network

  storage:
    image: harbor.treok.eu/devops_project_nctesa/storage:${STORAGE_TAG}
    build: ./storage
    container_name: storage
    restart: "always"
    expose:
      - "6000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      postgres:
        condition: service_started
    networks:
      - micro_network

  monitor_v1_1:
    image: harbor.treok.eu/devops_project_nctesa/monitor:${MONITOR_TAG}
    build: ./monitor
    container_name: monitor${SERVICE_NAME_SUFFIX}
    restart: "on-failure:5"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PROJECT_USERNAME=${PROJECT_USERNAME}
      - PROJECT_PASSWORD=${PROJECT_PASSWORD}
    expose:
      - "8198"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service1_v1_1
      - service2_v1_1
      - storage
    networks:
      - micro_network

  postgres:
    image: postgres:17.6-alpine
    container_name: postgres
    restart: "on-failure:5"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - micro_network

  api-gateway:
    image: harbor.treok.eu/devops_project_nctesa/api-gateway:${GATEWAY_TAG}
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8198:8198"
      - "8199:8199"
    volumes:
      - ./api-gateway/nginx/certs:/etc/nginx/certs:ro
      - ./api-gateway/nginx/api_state:/etc/nginx/api_state
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - micro_network

volumes:
  pg_data:

networks:
  micro_network:
